### ISSUE TITLE
Markdown Table Support

### ISSUE THREAD

**Issue by johnbeech** [bbc/morty-docs#22]
**Is your feature request related to a problem? Please describe.**
Markdown tables not rendered correctly:
- https://broxy.tools.bbc.co.uk/morty-docs/act-test-example/README.html

For example, currently:
<img width="257" alt="Screenshot 2020-01-15 at 10 03 11" src="https://user-images.githubusercontent.com/6341696/72424676-461e0180-377e-11ea-94c0-f06ad0c2fad0.png">

Usually get rendered in github to:

<img width="320" alt="Screenshot 2020-01-15 at 10 04 03" src="https://user-images.githubusercontent.com/6341696/72424745-6221a300-377e-11ea-86a5-f0dbd99f7227.png">

**Describe the solution you'd like**

Mark down tables rendered as HTML tables when published via morty-docs.

**Additional context**

We use lots of tables in our documentation; this would be an improvement on multiple pages.

**Comment by stephegn** [comment]
Heya, 

We use [Showdown](https://github.com/showdownjs/showdown) in GitHub flavoured mode but it does look like it is being a bit more picky than GitHub here.

If you add an extra dash in your separator it seems to be happier:

```
| # | Table | 
| -- | -- |
| 1 | Thing |
```
Feel free to reopen this issue if this doesn't work for you :)

**Comment by stephegn** [comment]
There is a better explanation than mine here: https://github.com/showdownjs/showdown/issues/666
