### ISSUE TITLE
Enable viewing other documents in the same directory / directory navigation

### ISSUE THREAD

**Issue by drpacman** [bbc/morty-docs#31]
**Is your feature request related to a problem? Please describe.**
When deep linking into documents published by Morty one hits a dead end. 
For example if I browse a fascincating ADR published by a team
https://broxy.tools.bbc.co.uk/morty-docs/web/architecture/adr-046-content-direction.html

There isn't an obvious way in the page to navigate to view the other ADR's in that directory without munging the URL by hand. It reduces the opportunity to learn once ones interest has been piqued!

**Describe the solution you'd like**
A link to the companion index page whenever one is present
Example from above (hand crafted by guessing!)
https://broxy.tools.bbc.co.uk/morty-docs/web/architecture/index.html

**Comment by stephegn** [comment]
You can now access parent pages through the breadcrumb navigation 🎉 
https://broxy.tools.bbc.co.uk/morty-docs/web/architecture/adr-046-content-direction.html
