### ISSUE TITLE
Links from repository root are incorrect when website is hosted with a prefix

### ISSUE THREAD

**Issue by paulbrimicombe** [bbc/morty-docs#32]
**Describe the bug**

* In GitHub Flavoured MarkDown, a link starting with `/`, e.g. `[my text](/some/path/to/file.md)` links to the path provided relative to the root of the repository.
* Sites are often hosted with a top-level prefix (e.g. sites hosted on [`morty`](https://broxy.tools.bbc.co.uk/morty-docs))
* `morty-docs` currently does not support setting a top-level prefix when generating the HTML and so these links are broken.
* For example, the links at the top of [this document](https://broxy.tools.bbc.co.uk/morty-docs/fabl/architecture/README.html) are broken when hosted on `broxy` using `morty` but are fine when viewed in [GitHub](https://github.com/bbc/fabl/blob/master/architecture/README.md)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a link relative to the root of the repository in a markdown file
2. Convert to HTML
3. Host on a site with a top-level prefix (e.g. `morty`)
4. See the broken links

**Expected behaviour**
Support should be available to add a top-level prefix to MarkDown links starting with `/`.

**Additional context**
Is this a bug or a missing feature?

**Comment by paulbrimicombe** [comment]
I'd be happy to look into fixing this but I'd like to talk about the approach first so that I don't head off in a direction that's not appropriate for some reason.

**Comment by adamjc** [comment]
Thanks for the issue Paul! I at least, certainly did not realise `/` links in GHFM are relative 😬, not sure how I feel about that feature, haha.

This is _probably_ a bug -- happy to talk about this one more. We'll put it on our backlog!

**Comment by paulbrimicombe** [comment]
> Thanks for the issue Paul! I at least, certainly did not realise `/` links in GHFM are relative 😬, not sure how I feel about that feature, haha.
> 
> This is _probably_ a bug -- happy to talk about this one more. We'll put it on our backlog!

They are relative but to the repository root (basically `/` is the root of the repo, not the root folder on your mac / linux box). I might ping you on slack later to have a quick chat if that's OK.

**Comment by paulbrimicombe** [comment]
Fixed by #34
