### ISSUE TITLE
Running locally requires node 12

### ISSUE THREAD

**Issue by crosslandwa** [bbc/morty-docs#35]
**Describe the bug**
Morty-docs will not run locally when using a node version < 12

When running `npm start` the following appears in the logs
```
error TypeError: dirPaths.flat is not a function
    at getDirectoryPaths (/path/to/morty-docs/build/src/helpers/get-directory-paths.js:16:31)
    at generateIndexes (/path/to/morty-docs/build/src/generate-indexes.js:32:23)
    at transform (/path/to/morty-docs/build/src/transform.js:26:21)
    at mortyDocs (/path/to/morty-docs/run.js:12:17)
```

**To Reproduce**
1. On a system using node 10
2. Run `npm ci`
3. Then run `npm start`

**Expected behavior**
I expect the documentation to tell me node 12 is required

**Additional context**
It may be worth updating `package.json` to explitily state node 12 (or above) is required via
```
"engines" : { "node" : ">=0.12" },
"engineStrict" : true
```

**Comment by adamjc** [comment]
Yeah, `flat` is introduced in Node 12 as part of it upgrading to V8 7.4.

**Comment by tsadler1988** [comment]
IMO #29 addresses this well enough.

**Comment by adamjc** [comment]
as an aside, `engineStrict` is not a part of npm anymore ([since 3.0](https://docs.npmjs.com/files/package.json#enginestrict))

And using `engines` would only produce a warning on installing it as a dependency, however I still think it's worth adding.

This won't fix your issue, however. I guess it would help to be more familiar with what features are available in different versions of node.

We could update the README to be more explicit about this? Let me know what you think.

**Comment by adamjc** [comment]
Using something like https://www.npmjs.com/package/avn will make the versions switch automatically if there's a `.node-version` file present in the folder, that might be of interest

**Comment by adamjc** [comment]
_or_ you could just always use `lts`, as node is mostly backwards compatible, and only switch to older versions if you have to, which is my preferred approach. YMMV

**Comment by crosslandwa** [comment]
I'd missed that there is already a `.node-version` - for me that is sufficient "advertisement" that node 12 is *required* to run locally and this issue can be closed as developer error

I agree with @adamjc that adding `engines` is worthwhile to warn clients consuming this as a library (this is a separate issue to what i've raised here)
