### ISSUE TITLE
Date ordering behaviour - unhandled edge cases

### ISSUE THREAD

**Issue by tsadler1988** [bbc/morty-docs#39]
**Describe the bug**
There are unhandled edge cases around Morty's [date ordering behaviour (if files are prefixed with a date in the format YYYY-MM-DD, they are sorted as most recent at the top)](https://github.com/bbc/morty-docs/blob/master/src/helpers/filter-files-in-dir.js#L3):
- Only supports this particular date format. Is this correct? A mixture of date formats will prevent the sorting from working correctly.
- A mix of dated and non-dated files can result in dated files not being grouped together, depending on ordering of files.

**To Reproduce**
See failing unit test on [mixed-dated-files-ordering-issue branch](https://github.com/bbc/morty-docs/tree/mixed-dated-files-ordering-issue).

**Expected behaviour**
One or both of:
- More date formats should be supported
- Dated files should be grouped together

Also worth considering whether the current behaviour should be configurable, rather than always on.

**Comment by adamjc** [comment]
At the very least we should be explicit about the opinions that are currently used.

I'm happy 

>A mix of dated and non-dated files can result in dated files not being grouped together, depending on ordering of files.

I don't see how this is possible, it currently appears to be using lexical sorting, 0-9 < a-z, so dates should always be sorted before text, right? 

Mixing date formats will definitely have issues in sorting.

**Comment by tsadler1988** [comment]
> I don't see how this is possible, it currently appears to be using lexical sorting, 0-9 < a-z, so dates should always be sorted before text, right?
Managed to add a failing test to my branch showing this.

**Comment by adamjc** [comment]
We've decided this is not a bug, but instead a convention that people need to follow, re: naming files. Lexical sorting behaves in this way, and the easiest 'fix' is to have a standard naming convention of files in the repo that is being targeted.

We will update the documentation to make clearer how sorting of files works, and perhaps update the function to be called `sortByLexicalDate`.

There's a discussion to be had around morty-docs, in that should it be making any assumptions about how files should be sorted?

**Comment by tsadler1988** [comment]
> There's a discussion to be had around morty-docs, in that should it be making any assumptions about how files should be sorted?

Yeah that was my thinking when I raised the issue:

> Also worth considering whether the current behaviour should be configurable, rather than always on.

I guess it's one of those things when moving an internal project to open source; it retains default logic that makes sense for internal use cases.

**Comment by stephegn** [comment]
This has been added as a known issue in the docs
