### ISSUE TITLE
Morty makes use of third-party hosted resources

### ISSUE THREAD

**Issue by LloydW93** [bbc/morty-docs#42]
A Morty page loads:

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
https://use.fontawesome.com/releases/v5.8.1/css/all.css

These are third-party resources distributing sites, with which the BBC does not have H&H approved, or any control over the content of. Since these are CSS it's relatively low risk, but it could be possible for a malicious actor (potentially with legitimate access to these hosting endpoints), to change the resources at the URLs, or to leak some information about the referrer through access logs.

I'd suggest this could be fixed along with #38.

**Comment by stephegn** [comment]
Hi Lloyd,
Thanks for the feedback!
Sounds reasonable, I agree with your suggestion of tackling this with #38, we will see how that progresses first.

**Comment by fuzzyfelt** [comment]
This has now been addressed.
