### ISSUE TITLE
Directories in indexes are not in any order

### ISSUE THREAD

**Issue by stephegn** [bbc/morty-docs#49]
**Describe the bug**🐞
When the index produced by morty-docs contains directories these are presented in a random order.

**Expected behavior** 👨‍💻👩‍💻 
Directories should be ordered the same way as files

**Screenshots** 📷
![Screenshot 2020-07-20 at 17 15 01](https://user-images.githubusercontent.com/3418146/87960686-91f29000-caac-11ea-922a-dd9841e0f759.png)

cc @niklasR

**Comment by stephegn** [comment]
Looks like we sort files https://github.com/bbc/morty-docs/blob/master/src/helpers/filter-files-in-dir.js#L4 but not directories https://github.com/bbc/morty-docs/blob/master/src/helpers/filter-dirs-in-dir.js

**Comment by andysteadbbc** [comment]
PR Created
https://github.com/bbc/morty-docs/pull/66
