### ISSUE TITLE
Move build job to GitHub actions

### ISSUE THREAD

**Issue by stephegn** [bbc/morty-docs#55]
Since Travis will no longer build OSS, move to GitHub actions instead.

**Comment by TimPerry** [comment]
Got status checks for PRs working and we have removed the old travis stuff.

Next up: get the publish workflow working. We have something in place but it won't work until we get the NPM token sorted.

**Comment by TimPerry** [comment]
Merged in two dependabot PRs which we can use to test a release when we get the token.

**Comment by RichardTribe** [comment]
I have added a repo secret called NPM_TOKEN to the morty-docs repo.
The value of this is the same token used when we set up travis for morty-docs.
It belongs to the npm user called 'itv-ci-machine'
