### ISSUE TITLE
Don't override existing index files

### ISSUE THREAD

**Issue by paulbrimicombe** [bbc/morty-docs#90]
# Problem

- All index files are generated automatically, even if the user has supplied an `index.md` file in their repository
- This prevents users from defining their own top-level landing page / controlling the end-user's navigation through the site

# Solution

- If an `index.html` file has already been created for a given folder, don't override it with a generated one.

e.g. Ideally this page: https://broxy.tools.bbc.co.uk/morty-docs/fabl/ would actually look like this: https://broxy.tools.bbc.co.uk/morty-docs/fabl/README.html

**Comment by stephegn** [comment]
Heya @paulbrimicombe! 
While this does expand the functionality of morty-docs a bit we think this change makes sense - the current behaviour certainly seems wrong.

We are happy to include this without a flag but it probably needs a note in the README. I'll also raise an issue for the docs on our internal system.

**Comment by paulbrimicombe** [comment]
Thanks @stephegn, I'll add a note in the README describing the new behaviour.

**Comment by paulbrimicombe** [comment]
@stephegn I've added a quick note to the README about index file generation in the PR...

**Comment by stephegn** [comment]
Fixed by #91
